export default function Footer() {
  return (
    <footer className="w-full py-8 mt-12 border-t border-border bg-card">
      <div className="container mx-auto px-4 text-center text-sm text-gray-500">
        <p>© {new Date().getFullYear()} AI Image Curator. Built with Next.js and Cosmic.</p>
        <p className="mt-2 text-xs">
          Images generated by Pollinations.ai
        </p>
      </div>
    </footer>
  );
}